name: financial_analyst_env
channels:
  - conda-forge
dependencies:
  # Dependencies for PostgreSQL database
  - python=3.8
  - pandas
  - sqlalchemy
  - psycopg2
  - python-dotenv
  - pyyaml
  - jupyter
  - alembic
  - ipython
  - postgresql

  # Dependencies for AstraDb vector database
  - openai
  - pypdf
  - astrapy

  # Dependencies for finBERT
  - numpy
  - nltk
  - tqdm
  - ipykernel
  - transformers
  - pip
  - pip:
    - joblib
    - scikit-learn
    - spacy
    - torch
    - textblob