name: financial_analyst_env
channels:
  - conda-forge
dependencies:
  # Dependencies for PostgreSQL database
  - python=3.12
  - pandas
  - sqlalchemy
  - psycopg2
  - python-dotenv
  - pyyaml
  - jupyter
  - alembic
  - ipython
  - postgresql

  # Dependencies for AstraDb vector database
  - openai
  - pypdf
  - astrapy

  # Dependencies for finBERT
  - numpy
  - nltk
  - tqdm
  - ipykernel
  - transformers
  - pip
  - pytorch
  - pip:
    - joblib
    - scikit-learn
    - spacy
    - torch
    - textblob

  # Dependencies for langchain tools for cleaning pdf and excel files 
  - pdfminer.six
  - pip:
    - pymupdf
    - langchain-astradb
    - langchain-huggingface
  - openpyxl
  - xlrd
  - xlwt
  - xlsxwriter
  - langchain-community
  