# Central YAML configuration file (Contains configuration data, no class here)

# API keys
api_keys:

  # Hugging Face API key
  huggingface: ${HUGGINGFACE_API_KEY}
  # OpenAI API key
  openai: ${OPENAI_API_KEY}
  
