 # SQL database-specific configurations (Contains configuration data, no class here)
postgresql_db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}